baseurl: https://joemo.dev
languageCode: en-us
theme: stack
paginate: 5
title: Joe Mo

languages:
    en:
        languageName: English
        title: Joe Mo
        weight: 1
    zh-cn:
        languageName: 中文
        title: 莫宇舟
        weight: 2

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /blog/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        enabled: true

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 PST

    sidebar:
        emoji: 💻
        subtitle: Computer Science, UC Berkeley
        avatar:
            enabled: true
            local: false
            src: /img/avatar.jpg

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site: jo3_mo

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: linkedin
          name: Twitter
          url: https://linkedin.com/in/yuzhoumo
          weight: 1
          params:
              icon: brand-linkedin

        - identifier: github
          name: GitHub
          url: https://github.com/yuzhoumo
          weight: 2
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com/jo3_mo
          weight: 3
          params:
              icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
