baseurl: https://joemo.dev/
languageCode: en-us
paginate: 3
title: Joe Mo
copyright: Joe Mo

# code highlight
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

params:
  mode: toggle  # color-mode: light, dark, toggle or auto
  useCDN: false # serve fonts and icons locally

  author: Joe Mo
  avatar: /img/avatar.jpg
  bio: Hey there! I'm studying Computer Science and Data Science at UC
       Berkeley. Welcome to my personal site!

  social:
    - name: LinkedIn
      icon: linkedin
      url: https://linkedin.com/in/yuzhoumo

    - name: GitHub
      icon: github
      url: https://github.com/yuzhoumo

    - name: Twitter
      icon: twitter
      url: https://twitter.com/jo3_mo

menu:
  main:
    - name: home
      url: /
      weight: 1

    - name: about
      url: /about
      weight: 2

    - name: posts
      url: /posts
      weight: 3
