baseurl: https://joemo.dev/
languageCode: en-us
paginate: 3
title: Joe (Yuzhou) Mo
copyright: Joe (Yuzhou) Mo
enableRobotsTXT: true

params:
  description: A personal blog for my little corner of the web

  mode: toggle             # color-mode: light, dark, toggle or auto
  useCDN: false            # serve fonts and icons locally
  openLinksInNewTab: true  # opens external links in new tab
  favicon: true            # includes favicon files in header

  navtitle: joemo.dev      # navbar main link text
  cursorAnimation: true    # show blinking cursor animation in navbar

  author: Joe (Yuzhou) Mo
  avatar: /img/avatar.jpg
  bio: Hey there, I'm Joe. Welcome to my little corner of the web!

  social:
    - name: LinkedIn
      icon: linkedin
      url: https://linkedin.com/in/yuzhoumo

    - name: GitHub
      icon: github
      url: https://github.com/yuzhoumo

    - name: Twitter
      icon: twitter
      url: https://twitter.com/jo3_mo

menu:
  main:
    - name: home
      url: /
      weight: 1

    - name: about
      url: /about
      weight: 2

    - name: posts
      url: /posts
      weight: 3

    - name: projects
      url: /projects
      weight: 4

markup:
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    tabWidth: 2
